### ISSUE TITLE
无法搜索到他人房间

### ISSUE THREAD

**Issue by South-River** [bieberg0n/broadcast-helper#1]
网络环境
windows 电脑A，windows电脑B，ubuntu电脑C
通过wireguard连接，防火墙均已关闭，可以相互ping通
测试游戏
文明6
电脑B已开房，电脑A搜索房间，并发出广播数据包。
将config.json5修改，从wireshark抓包确认了数据包已从电脑A通过client.py发送至电脑C，再通过C上运行的serv.py发送至电脑A,B。
发出的数据包源ip为电脑A，目的ip有电脑A与B。
但是无法搜索进入房间。同时电脑B会返回ICMP协议的destination unreachable(port unreachable)
![60814ae0887307.jpg](https://user-images.githubusercontent.com/52597530/212556939-46cf0fff-3aa2-4837-b978-213723b8fcd0.jpg)

**Comment by bieberg0n** [comment]
文明6不是自带联机么…
192.168.6.x是wireguard的网段吗？图片里是电脑B在监听网络包吗，然后电脑B的wireguard ip是192.168.6.3？
我开发这个主要用于红警的联机，我也不太清楚为何你的电脑B会返回destination unreachable，也许是文明6未监听wireguard网卡的相应端口？

**Comment by South-River** [comment]
> 文明6不是自带联机么…
> 192.168.6.x是wireguard的网段吗？图片里是电脑B在监听网络包吗，然后电脑B的wireguard ip是192.168.6.3？
> 我开发这个主要用于红警的联机，我也不太清楚为何你的电脑B会返回destination unreachable，也许是文明6未监听wireguard网卡的相应端口？

是的。不过可用，已解决，谢啦。
